# Generated by Django 5.2.13 on 2026-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="page",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name="page",
            table="pages",
        ),
    ]
