# Generated by Django 5.2.13 on 2026-04-25 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_options_booking_total_price_and_more"),
        ("core", "0003_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="package",
        ),
        migrations.AddField(
            model_name="bookingitem",
            name="package_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="bookingitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
    ]
