# Generated by Django 5.2.13 on 2026-04-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seo",
            old_name="description",
            new_name="meta_description",
        ),
        migrations.RenameField(
            model_name="seo",
            old_name="title",
            new_name="meta_title",
        ),
    ]
