# Generated by Django 5.2.13 on 2026-04-18 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_rename_description_seo_meta_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "city_pages",
                "ordering": ["city"],
            },
        ),
        migrations.RenameField(
            model_name="seo",
            old_name="meta_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="seo",
            old_name="meta_title",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="page",
        ),
        migrations.AddField(
            model_name="seo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seo",
            name="page_slug",
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seo",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="seo",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name="seo",
            table="seo_meta",
        ),
    ]
