# Generated by Django 5.2.13 on 2026-04-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="lead",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("converted", "Converted"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterModelTable(
            name="lead",
            table="leads",
        ),
    ]
