# Generated by Django 5.2.13 on 2026-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_booking_time_alter_booking_user_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="budget",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="guests",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="hours",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="location",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AlterField(
            model_name="lead",
            name="style",
            field=models.CharField(default="N/A", max_length=50),
        ),
        migrations.AlterField(
            model_name="lead",
            name="videography",
            field=models.CharField(default="No", max_length=10),
        ),
    ]
