# Generated by Django 5.2.13 on 2026-04-18 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="gallery",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="gallery/photos/"),
        ),
        migrations.AlterModelTable(
            name="gallery",
            table="galleries",
        ),
        migrations.AlterModelTable(
            name="photo",
            table="photos",
        ),
    ]
